Closes #58
papercups-io/papercups_flutter pull request #66
Opened 2021-05-11 16:41 UTC by ryg-git

2021-05-12 06:46 UTC, aguilaair reviewed
Looking good. Just a few notes to improve the end user experience.

Thanks for your awesome work!

2021-05-12 06:46 UTC, aguilaair commented on lib/widgets/sendMessage.dart
> +    if (kIsWeb) {
Ideally we'd need an implementation that works on desktop too

2021-05-12 06:46 UTC, aguilaair commented on lib/widgets/sendMessage.dart
> +            print('sendMessage: Error in file picker: $e');
This is Ok for debugging, but let's make sure that the user gets feedback that something has gone wrong, possibly with a toast

2021-05-12 06:46 UTC, aguilaair commented on lib/widgets/sendMessage.dart
> +        onPressed: () {},
Let's let the user know that this feature is not currently supported on their platform, or directly hide it.

2021-05-12 15:36 UTC, ryg-git commented
@aguilaair thanks for the review, I will implement the needful changes.

2021-05-12 15:38 UTC, aguilaair commented
Ok, thank again for putting your time into this feature! I appreciate it.

2021-05-15 20:56 UTC, aguilaair approved these changes
Looks good, I'll do some minor changes and see of I can implement support for Windows and MacOS than i think it is ready to merge!

Thanks for you help 😃

2021-05-16 12:14 UTC, aguilaair requested changes
This implementation currently does not work with Web. `dart:io` is used and is therefore is incompatible with web. Additionally, the file picker will always return a `Uint8List` in web as paths aren't supported. If you have a chance to fix it it would be great!

2021-05-16 17:11 UTC, ryg-git commented
I will fix it as soon as I can thanks for the  review @aguilaair

2021-05-16 18:22 UTC, aguilaair commented
Thank you for your effort! I really appreciate it.

2021-05-18 14:09 UTC, ryg-git commented
@aguilaair I have tested attachment upload and download on android device and on web (chrome), I am not able to test it on iOS device if it is possible for you to test it on iOS please do although I don't think it will not work on iOS. If you want anything changed please let me know.

Thank you!

2021-05-18 14:12 UTC, aguilaair commented
Great! I'll check it out ASAP

2021-05-23 12:21 UTC, aguilaair approved these changes

2021-05-23 12:23 UTC, aguilaair commented
Looks great! Made a few tewaks to show the body even if an attachment is shown and also tweaked some alerts to be more neutral themed.

Thanks for your effort. I believe this can now be merged and it will be included in the next release!

2021-05-23 12:23 UTC, merged